name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Copy README
      run: |
        cp README.md ./megalodon/
        cp LICENSE.txt ./megalodon/
    - name: Install dependencies
      run: |
        yarn install
    - name: Build
      run: |
        yarn workspace @mashirozx/megalodon run build
    - name: Publish
      run: |
        yarn workspace @mashirozx/megalodon publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
